version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: stockfinder_db
    restart: always
    environment:
      POSTGRES_USER: romeoshahaj
      POSTGRES_PASSWORD: strongpassword123
      POSTGRES_DB: stockFinder
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: stockfinder_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${DB_CONN}
      - JWT__SigningKey=${JWT_KEY}
      - JWT__Issuer=${JWT_ISSUER}
      - JWT__Audience=${JWT_AUDIENCE}
      - FMPKey=${FMP_KEY}
    depends_on:
      - postgres

volumes:
  pgdata:
