version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: stockfinder_db
    restart: always
    environment:
      POSTGRES_USER: romeoshahaj
      POSTGRES_PASSWORD: strongpassword123
      POSTGRES_DB: stockFinder
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: stockfinder_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Username=romeoshahaj;Password=strongpassword123;Database=stockFinder
      - JWT__SigningKey=J//qQNHXZjzkAVlkbKsGSuTQq+U06fbM8dZusEcukG3YP3hRLkq+Jpn6hrQno8kt
      - JWT__Issuer=http://localhost:8080
      - JWT__Audience=http://localhost:8080
      - Lt8BF8yWDmlNVclt+I3QWw==
      - FMPKey=jhS8N39e1zPn0jVMLdU6yM9FXg0EtqpU
    depends_on:
      - postgres

volumes:
  pgdata:
